version: '3.8'

services:
  cosmosdb-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: cosmosdb-emulator
    ports:
      - "8081:8081"
      - "10250:10250"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=4
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    volumes:
      - cosmosdb-data:/var/lib/cosmosdb/data
    restart: unless-stopped

volumes:
  cosmosdb-data:
